version: '3.8'
services:
  payment-service:
    build: .
    container_name: payment_service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - MOCK_SUCCESS_RATE=0.8
      - MOCK_DELAY_MS=1500
    restart: unless-stopped
